development:
  host: localhost
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>
  adapter: postgresql
  database: vex-production
production:
  host: localhost
  username: <%= ENV["DB_USERNAME"] %> 
  password: <%= ENV["DB_PASSWORD"] %>
  adapter: postgresql
  database: vex-production

